"""Added vote total collumns to post and comment tables

Revision ID: 639758679d7b
Revises: 
Create Date: 2025-08-06 19:01:06.296298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '639758679d7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_vote_total', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('post_vote_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_vote_total')
    op.drop_column('comment', 'comment_vote_total')
    # ### end Alembic commands ###
